Adding docker flag to solve build errors.
To solve the following errors when building with Docker, flag "--network host" is to be used.

fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz                                                                              
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)                                                                 
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory                                                                                    
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz                                                                         
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)                                                            
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory

Afterwards the build is smooth.

As info I'm adding the stackverflow solution to the errors, where I got the fix: https://stackoverflow.com/questions/53710206/docker-cant-build-because-of-alpine-error